export const strings = {
  appName: "Luminor",
  tabs: {
    home: "Home",
    threads: "Threads",
    search: "Search",
    sessions: "Sessions",
    settings: "Settings",
  },
  connection: {
    connected: "Connected",
    connecting: "Connecting",
    disconnected: "Disconnected",
    incompatible: "Incompatible",
    reconnect: "Reconnect",
    disconnect: "Disconnect",
    forgetPairing: "Forget pairing",
    server: "Server",
    instance: "Instance",
    build: "Build",
    protocol: "Protocol",
    lastError: "Last error",
    paired: "Paired",
    notPaired: "Not paired",
    sheetTitle: "Connection",
  },
  status: {
    active: "Active",
    idle: "Idle",
    running: "Running",
    needsAttention: "Needs attention",
  },
  screens: {
    home: "Home",
    threads: "Threads",
    search: "Search",
    sessions: "Sessions",
    settings: "Settings",
    workspace: "Workspace",
    thread: "Thread",
  },
  empty: {
    homeTitle: "No workspaces yet",
    homeBody: "Connect to a Luminor server to see spaces, projects, and threads.",
    threadsTitle: "No threads",
    threadsBody: "Threads from the connected server will appear here.",
    searchTitle: "Search",
    searchBody: "Search across loaded threads once the app is connected.",
    sessionsTitle: "No sessions",
    sessionsBody: "Host terminals and sessions are not part of this mobile cut.",
    workspaceTitle: "Workspace",
    workspaceBody: "Workspace detail will appear here after the Home screen lands.",
    threadTitle: "Thread",
    threadBody: "Timeline, chat, and composer will appear here.",
  },
  settings: {
    title: "Settings",
    serverSection: "Server",
    serverUrl: "Server URL",
    serverUrlPlaceholder: "http://luminor.tailnet.ts.net:3773",
    saveUrl: "Save URL",
    pairingSection: "Pairing",
    pairingCredential: "Pairing credential",
    pairingPlaceholder: "One-time pairing token",
    pair: "Pair device",
    pairing: "Pairing…",
    connectionSection: "Connection",
    testConnection: "Test /health",
    testing: "Testing…",
    healthOk: "Server is reachable",
    themeNote: "Dark theme only for this release.",
    version: "App version",
    urlSaved: "Server URL saved.",
    pairedOk: "Device paired.",
    state: "State",
    compatibility: "Compatibility",
  },
  common: {
    showMore: "Show more",
    manage: "Manage",
    viewAll: "View all",
    notifications: "Notifications",
    close: "Close",
  },
  thread: {
    workingFor: "Working for",
    started: "Started",
    sendPlaceholder: "Send a follow-up command…",
    send: "Send",
    interrupt: "Stop",
    approve: "Approve",
    deny: "Deny",
    taskProgress: "Task progress",
    editedFilesOne: "Edited 1 file",
    editedFilesMany: "Edited {count} files",
    more: "More",
    approvalTitle: "Approval required",
    pickModel: "Choose model",
    modelsUnavailable: "Could not load models.",
    noModels: "No models available for this provider.",
    session: "Session",
    sessionError: "Session error",
    emptyTitle: "No activity yet",
    emptyBody: "Send a follow-up to start this thread.",
    loading: "Loading thread…",
    missing: "Thread not found.",
    justNow: "just now",
    minutesShort: "{count}m",
    minutesAgo: "{count}m ago",
    hoursAgo: "{count}h ago",
    daysAgo: "{count}d ago",
    modified: "Modified",
    inProgress: "In progress",
    pending: "Pending",
    running: "Running",
    expand: "Expand",
    collapse: "Collapse",
    viewSession: "View session",
    sending: "Sending",
    stopping: "Stopping",
  },
} as const;
