export const strings = {
  appName: "Luminor",
  tabs: {
    home: "Home",
    threads: "Threads",
    search: "Search",
    sessions: "Sessions",
    settings: "Settings",
  },
  connection: {
    connected: "Connected",
    connecting: "Connecting",
    disconnected: "Disconnected",
    incompatible: "Incompatible",
    reconnect: "Reconnect",
    disconnect: "Disconnect",
    forgetPairing: "Forget pairing",
    server: "Server",
    instance: "Instance",
    build: "Build",
    protocol: "Protocol",
    lastError: "Last error",
    paired: "Paired",
    notPaired: "Not paired",
    sheetTitle: "Connection",
  },
  status: {
    active: "Active",
    idle: "Idle",
    running: "Running",
    needsAttention: "Needs attention",
  },
  screens: {
    home: "Home",
    threads: "Threads",
    search: "Search",
    sessions: "Sessions",
    settings: "Settings",
    workspace: "Workspace",
    thread: "Thread",
  },
  empty: {
    homeTitle: "No workspaces yet",
    homeBody: "Connect to a Luminor server to see spaces, projects, and threads.",
    threadsTitle: "No threads",
    threadsBody: "Threads from the connected server will appear here.",
    searchTitle: "Search",
    searchBody: "Search across loaded threads once the app is connected.",
    sessionsTitle: "No sessions",
    sessionsBody: "Host terminals and sessions are not part of this mobile cut.",
    workspaceTitle: "Workspace",
    workspaceBody: "Workspace detail will appear here after the Home screen lands.",
    threadTitle: "Thread",
    threadBody: "Timeline, chat, and composer will appear here.",
  },
  settings: {
    title: "Settings",
    serverSection: "Server",
    serverUrl: "Server URL",
    serverUrlPlaceholder: "http://luminor.tailnet.ts.net:3773",
    saveUrl: "Save URL",
    pairingSection: "Pairing",
    pairingCredential: "Pairing credential",
    pairingPlaceholder: "One-time pairing token",
    pair: "Pair device",
    pairing: "Pairing…",
    connectionSection: "Connection",
    testConnection: "Test /health",
    testing: "Testing…",
    healthOk: "Server is reachable",
    themeNote: "Dark theme only for this release.",
    version: "App version",
    urlSaved: "Server URL saved.",
    pairedOk: "Device paired.",
    state: "State",
    compatibility: "Compatibility",
  },
  common: {
    showMore: "Show more",
    manage: "Manage",
    viewAll: "View all",
    notifications: "Notifications",
    close: "Close",
  },
  sessionsUi: {
    emptyTitle: "Terminal sessions appear here",
    emptyBody:
      "Host terminals live on the Luminor desktop. This app has no session-list RPC, so there is nothing truthful to show yet. Rows will land here when the server exposes a terminal inventory.",
    disconnectedHint: "Connect to a server first. Pairing and health live in Settings.",
    connectingHint: "Connecting to the server…",
    incompatibleHint: "This app and server are incompatible. Open Settings to inspect the protocol.",
  },
  settingsUi: {
    pairingStatus: "Pairing",
    healthResult: "Last health check",
    healthStarting: "starting",
    healthReady: "ready",
    healthNotReady: "not ready",
    healthUnknown: "unknown",
    projection: "Projection",
    pushBus: "Push bus",
    startup: "Startup",
    forgetConfirmTitle: "Forget pairing?",
    forgetConfirmBody: "This removes the stored session token and disconnects from the server.",
    cancel: "Cancel",
    confirmForget: "Forget pairing",
    aboutSection: "About",
    licenses: "Licenses",
    licensesTitle: "Open-source licenses",
    licensesSubtitle: "Key packages shipped in this app.",
    openConnectionSheet: "Connection details",
    capabilities: "Capabilities",
    theme: "Theme",
    pairHint: "Paste the one-time pairing token shown on the desktop host.",
    healthFailed: "Health check failed",
    none: "None",
    chevron: "›",
  },
} as const;
