export const strings = {
  appName: "Luminor",
  tabs: {
    home: "Home",
    threads: "Threads",
    search: "Search",
    sessions: "Sessions",
    settings: "Settings",
  },
  connection: {
    connected: "Connected",
    connecting: "Connecting",
    disconnected: "Disconnected",
    incompatible: "Incompatible",
    reconnect: "Reconnect",
    disconnect: "Disconnect",
    forgetPairing: "Forget pairing",
    server: "Server",
    instance: "Instance",
    build: "Build",
    protocol: "Protocol",
    lastError: "Last error",
    paired: "Paired",
    notPaired: "Not paired",
    sheetTitle: "Connection",
  },
  status: {
    active: "Active",
    idle: "Idle",
    running: "Running",
    needsAttention: "Needs attention",
  },
  screens: {
    home: "Home",
    threads: "Threads",
    search: "Search",
    sessions: "Sessions",
    settings: "Settings",
    workspace: "Workspace",
    thread: "Thread",
  },
  empty: {
    homeTitle: "No workspaces yet",
    homeBody: "Connect to a Luminor server to see spaces, projects, and threads.",
    threadsTitle: "No threads",
    threadsBody: "Threads from the connected server will appear here.",
    searchTitle: "Search",
    searchBody: "Search across loaded threads once the app is connected.",
    sessionsTitle: "No sessions",
    sessionsBody: "Host terminals and sessions are not part of this mobile cut.",
    workspaceTitle: "Workspace",
    workspaceBody: "Workspace detail will appear here after the Home screen lands.",
    threadTitle: "Thread",
    threadBody: "Timeline, chat, and composer will appear here.",
  },
  settings: {
    title: "Settings",
    serverSection: "Server",
    serverUrl: "Server URL",
    serverUrlPlaceholder: "http://luminor.tailnet.ts.net:3773",
    saveUrl: "Save URL",
    pairingSection: "Pairing",
    pairingCredential: "Pairing credential",
    pairingPlaceholder: "One-time pairing token",
    pair: "Pair device",
    pairing: "Pairing…",
    connectionSection: "Connection",
    testConnection: "Test /health",
    testing: "Testing…",
    healthOk: "Server is reachable",
    themeNote: "Dark theme only for this release.",
    version: "App version",
    urlSaved: "Server URL saved.",
    pairedOk: "Device paired.",
    state: "State",
    compatibility: "Compatibility",
  },
  common: {
    showMore: "Show more",
    manage: "Manage",
    viewAll: "View all",
    notifications: "Notifications",
    close: "Close",
  },
  threads: {
    filterAll: "All",
    filterActive: "Active",
    filterPinned: "Pinned",
    unfiled: "Unfiled",
    now: "now",
    minutesAgo: "{n}m ago",
    hoursAgo: "{n}h ago",
    daysAgo: "{n}d ago",
    loading: "Loading threads…",
    disconnectedTitle: "Not connected",
    disconnectedBody: "Connect to a Luminor server to see threads.",
    incompatibleTitle: "Server incompatible",
    incompatibleBody:
      "This app cannot talk to the connected server. Update one side and reconnect.",
    emptyAllTitle: "No threads",
    emptyAllBody: "Threads from the connected server will appear here.",
    emptyActiveTitle: "Nothing active",
    emptyActiveBody: "No threads are running or waiting for you right now.",
    emptyPinnedTitle: "Nothing pinned",
    emptyPinnedBody: "Pin a thread on desktop to keep it here.",
  },
  search: {
    placeholder: "Search threads",
    loading: "Loading threads…",
    promptTitle: "Search threads",
    promptBody: "Find loaded threads by title, project, or workspace.",
    noResultsTitle: "No matching threads",
    noResultsBody: "Try a different name, project, or workspace.",
    disconnectedTitle: "Not connected",
    disconnectedBody: "Connect to a Luminor server to search threads.",
    incompatibleTitle: "Server incompatible",
    incompatibleBody:
      "This app cannot talk to the connected server. Update one side and reconnect.",
    clear: "Clear search",
  },
  thread: {
    workingFor: "Working for",
    started: "Started",
    sendPlaceholder: "Send a follow-up command…",
    send: "Send",
    interrupt: "Stop",
    approve: "Approve",
    deny: "Deny",
    taskProgress: "Task progress",
    editedFilesOne: "Edited 1 file",
    editedFilesMany: "Edited {count} files",
    more: "More",
    approvalTitle: "Approval required",
    pickModel: "Choose model",
    modelsUnavailable: "Could not load models.",
    noModels: "No models available for this provider.",
    session: "Session",
    sessionError: "Session error",
    emptyTitle: "No activity yet",
    emptyBody: "Send a follow-up to start this thread.",
    missing: "Thread not found.",
    justNow: "just now",
    minutesShort: "{count}m",
    minutesAgo: "{count}m ago",
    hoursAgo: "{count}h ago",
    daysAgo: "{count}d ago",
    stopping: "Stopping",
  },
} as const;

export const homeStrings = {
  segmentSpaces: "Spaces",
  segmentActivity: "Activity",
  segmentPinned: "Pinned",
  workspaces: "Workspaces",
  recentThreads: "Recent threads",
  runningTerminals: "Running terminals",
  openSessions: "Open sessions",
  workspaceSubtitle: "Workspace",
  unassignedWorkspace: "Unassigned",
  projects: "Projects",
  threads: "Threads",
  terminals: "Terminals",
  loading: "Loading…",
  disconnectedTitle: "Disconnected",
  disconnectedBody: "Connect to a Luminor server to load spaces and threads.",
  emptyWorkspacesTitle: "No workspaces",
  emptyWorkspacesBody: "Spaces from the connected server will appear here.",
  emptyRecentTitle: "No recent threads",
  emptyRecentBody: "Threads you use will show up here.",
  emptyActivityTitle: "No activity",
  emptyActivityBody: "Active and running threads will appear here.",
  emptyPinnedTitle: "Nothing pinned",
  emptyPinnedBody: "Pin a thread to keep it here.",
} as const;

export const workspaceStrings = {
  projects: "Projects",
  threads: "Threads",
  runningTerminals: "Running terminals",
  pinned: "Pinned",
  chats: "Chats",
  threadKind: "Thread",
  threadSingular: "thread",
  threadPlural: "threads",
  viewAllChats: "View all chats",
  loading: "Loading workspace…",
  disconnectedTitle: "Disconnected",
  disconnectedBody: "Connect to a Luminor server to load this workspace.",
  notFoundTitle: "Workspace not found",
  notFoundBody: "This workspace is not in the current snapshot.",
  emptyPinnedTitle: "Nothing pinned",
  emptyPinnedBody: "Pinned threads in this workspace will appear here.",
  emptyProjectsTitle: "No projects",
  emptyProjectsBody: "Projects in this workspace will appear here.",
  emptyChatsTitle: "No chats",
  emptyChatsBody: "Threads in this workspace will appear here.",
} as const;
