// FILE: scenarios.ts
// Purpose: Static fixtures for the GitHub-issues-to-Kanban discovery prototype.
// Layer: Kanban prototype (mocked)

import type {
  PrototypeBoardCard,
  PrototypeIssue,
  PrototypeIssueFilters,
  PrototypeRepo,
} from "./issue-sync.types";

export const PROTOTYPE_REPOS: readonly PrototypeRepo[] = [
  { id: "repo-luminor", name: "Luminor" },
  { id: "repo-missiondeck", name: "MissionDeck" },
  { id: "repo-frontend", name: "frontend" },
];

export const EMPTY_PROTOTYPE_ISSUE_FILTERS: PrototypeIssueFilters = {
  query: "",
  repoIds: [],
  labels: [],
  states: [],
  kinds: [],
};

export const PROTOTYPE_ISSUES: readonly PrototypeIssue[] = [
  {
    id: "issue-1842",
    number: 1842,
    title: "Sync GitHub issues onto the Kanban board as drafts",
    body: "PRs already land on the board. Open issues should be filterable and optionally parked in Draft without dispatching a thread.\n\nAccepting an issue should not start work. It should create a Kanban draft that still points at this GitHub issue, so the source stays visible after it leaves the inbox.",
    repo: "Luminor",
    repoId: "repo-luminor",
    state: "open",
    kind: "enhancement",
    labels: ["kanban", "github"],
    author: "alegherix",
    assignee: "alegherix",
    comments: [
      {
        id: "c-1842-1",
        author: "nara",
        body: "Please keep GitHub state untouched. The board owns Draft / In Progress / Done.",
        updatedAt: "3h ago",
      },
      {
        id: "c-1842-2",
        author: "alegherix",
        body: "Yes — Accept is only “put this on my board”. Sending the draft later starts the thread.",
        updatedAt: "2h ago",
      },
    ],
    updatedAt: "2h ago",
  },
  {
    id: "issue-1831",
    number: 1831,
    title: "Kanban PR filter misses closed draft pull requests",
    body: "Filtering the board by PR state does not join the live pullRequests.list for draft PRs that later closed.\n\nRepro: open a draft PR, close it, then filter the board by Merged / Blocked. The card still shows the stale draft badge.",
    repo: "Luminor",
    repoId: "repo-luminor",
    state: "open",
    kind: "bug",
    labels: ["kanban", "bug"],
    author: "alegherix",
    assignee: "alegherix",
    comments: [
      {
        id: "c-1831-1",
        author: "nara",
        body: "Same join bug we hit on lastKnownPr. Filter from the live list, not the thread snapshot.",
        updatedAt: "5h ago",
      },
    ],
    updatedAt: "5h ago",
  },
  {
    id: "issue-1798",
    number: 1798,
    title: "Triage inbox for incoming GitHub issues",
    body: "Keep noisy issues off the board until someone accepts them.\n\nInbox shows everything we can see on GitHub. The board only shows work we decided to keep. One issue at a time — read, then Accept or Skip.",
    repo: "Luminor",
    repoId: "repo-luminor",
    state: "open",
    kind: "enhancement",
    labels: ["kanban", "github"],
    author: "alegherix",
    assignee: null,
    comments: [
      {
        id: "c-1798-1",
        author: "alegherix",
        body: "No batch accept. If I cannot read it, it should not land on the board.",
        updatedAt: "1d ago",
      },
    ],
    updatedAt: "1d ago",
  },
  {
    id: "issue-1488",
    number: 1488,
    title: "Draft cards should show an issue number chip",
    body: "When a card is backed by a GitHub issue, show #number next to the title so it is distinguishable from a blank draft.\n\nThe chip is a source link, not a work state. Draft / In Progress / Done still come from the column.",
    repo: "Luminor",
    repoId: "repo-luminor",
    state: "open",
    kind: "enhancement",
    labels: ["kanban"],
    author: "nara",
    assignee: null,
    comments: [
      {
        id: "c-1488-1",
        author: "alegherix",
        body: "Clicking the chip should still open GitHub later. For now the number is enough.",
        updatedAt: "2d ago",
      },
    ],
    updatedAt: "2d ago",
  },
  {
    id: "issue-221",
    number: 221,
    title: "Dark mode contrast on empty board columns",
    body: "Dashed empty-state copy disappears against the dark column background.\n\nFixed by adding a hairline on cards and bumping the empty-state contrast. Closed so it should stay out of an open-only inbox filter.",
    repo: "Luminor",
    repoId: "repo-luminor",
    state: "closed",
    kind: "bug",
    labels: ["bug"],
    author: "nara",
    assignee: "alegherix",
    comments: [
      {
        id: "c-221-1",
        author: "nara",
        body: "Shipped. Leaving this in the fixture so Closed is testable.",
        updatedAt: "1w ago",
      },
    ],
    updatedAt: "1w ago",
  },
  {
    id: "issue-90",
    number: 90,
    title: "Document worktree environment badges on cards",
    body: "The local/worktree badge is easy to miss. Add a short note in the Kanban docs about what the badge means and when it appears.",
    repo: "Luminor",
    repoId: "repo-luminor",
    state: "open",
    kind: "docs",
    labels: ["docs"],
    author: "nara",
    assignee: null,
    comments: [],
    updatedAt: "3d ago",
  },
  {
    id: "issue-1566",
    number: 1566,
    title: "Auto-archive closed GitHub issues from intake",
    body: "Only open issues should stay intake-eligible. Closed issues should archive on sync so the inbox does not fill with finished work.\n\nSaved / already-accepted cards can keep their source link after the GitHub issue closes.",
    repo: "MissionDeck",
    repoId: "repo-missiondeck",
    state: "open",
    kind: "enhancement",
    labels: ["github", "intake"],
    author: "alegherix",
    assignee: "alegherix",
    comments: [
      {
        id: "c-1566-1",
        author: "nara",
        body: "Webhook `closed` should archive the inbox row, not the board card.",
        updatedAt: "8h ago",
      },
    ],
    updatedAt: "8h ago",
  },
  {
    id: "issue-1502",
    number: 1502,
    title: "Promote intake item should keep the GitHub source link",
    body: "Issue URL belongs in source metadata, not appended to the note body.\n\nIf we promote this later, the Kanban card should still show Luminor #1502 even though the body is just the description.",
    repo: "MissionDeck",
    repoId: "repo-missiondeck",
    state: "open",
    kind: "bug",
    labels: ["bug", "intake"],
    author: "alegherix",
    assignee: null,
    comments: [
      {
        id: "c-1502-1",
        author: "alegherix",
        body: "Strip trailing matching issue URLs from legacy inbox snapshots.",
        updatedAt: "12h ago",
      },
    ],
    updatedAt: "12h ago",
  },
  {
    id: "issue-412",
    number: 412,
    title: "Annotation tool crashes on large point clouds",
    body: "Opening a 12M-point scene OOMs the worker.\n\nNeed a tiled loader before this is board-worthy. This is the kind of issue that should stay in triage until someone actually wants to work it.",
    repo: "frontend",
    repoId: "repo-frontend",
    state: "open",
    kind: "bug",
    labels: ["bug"],
    author: "sara",
    assignee: "sara",
    comments: [
      {
        id: "c-412-1",
        author: "sara",
        body: "Reproduced on the 12M fixture. Chrome tab dies around 6GB.",
        updatedAt: "4h ago",
      },
    ],
    updatedAt: "4h ago",
  },
  {
    id: "issue-398",
    number: 398,
    title: "Keyboard shortcut for the label picker",
    body: "Adding a label on GitHub still feels like a full-page refresh. Local picker should be instant and keyboard-reachable.",
    repo: "frontend",
    repoId: "repo-frontend",
    state: "open",
    kind: "enhancement",
    labels: ["enhancement"],
    author: "sara",
    assignee: null,
    comments: [
      {
        id: "c-398-1",
        author: "sara",
        body: "Even a command-palette item would be enough.",
        updatedAt: "6d ago",
      },
    ],
    updatedAt: "6d ago",
  },
];

export const SEED_PROTOTYPE_BOARD_CARDS: readonly PrototypeBoardCard[] = [
  {
    id: "card-seed-draft",
    column: "draft",
    title: "Rewrite PR filter to join live pullRequests.list",
    source: "seed",
    issueId: null,
    issueNumber: null,
    repo: "Luminor",
    labels: [],
    preview: "Draft prompt ready — not dispatched.",
    meta: "Draft · Luminor",
  },
  {
    id: "card-seed-progress",
    column: "inProgress",
    title: "Add Draft to the Kanban work-state filter",
    source: "seed",
    issueId: null,
    issueNumber: null,
    repo: "Luminor",
    labels: [],
    preview: null,
    meta: "Working · 18m",
  },
  {
    id: "card-seed-done",
    column: "done",
    title: "Fix empty GitHub inbox after Connect",
    source: "seed",
    issueId: null,
    issueNumber: null,
    repo: "MissionDeck",
    labels: [],
    preview: null,
    meta: "Merged · PR #412",
  },
];
